### ISSUE TITLE
Runtime error in package 'pandas'

### ISSUE THREAD

**Issue by iridix** [lakshayg/google_benchmark_plot#2]
Results from google benchmark page [https://github.com/google/benchmark#basic-usage](https://github.com/google/benchmark#basic-usage) causes run-time error. Pyton traceback listed below, benchmark.csv attached as text file, change it extension to 'csv'.
[benchmark.txt](https://github.com/lakshayg/google_benchmark_plot/files/3362566/benchmark.txt)

```
>python plot.py -f benchmark.csv
Traceback (most recent call last):
  File "plot.py", line 116, in <module>
    main()
  File "plot.py", line 97, in main
    data = read_data(args)
  File "plot.py", line 74, in read_data
    data['input'] = data['name'].apply(lambda x: int(x.split('/')[1]))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "plot.py", line 74, in <lambda>
    data['input'] = data['name'].apply(lambda x: int(x.split('/')[1]))
IndexError: list index out of range
```

**Comment by lakshayg** [comment]
Hey there, thanks for reporting this. This is kind of a hacky script so I'm not surprised it failed. I have pushed a fix for the issue, it should work now. Also, feel free to send a PR if you find a bug and have a fix for it.
